######################################################################
# Automatically generated by qmake (2.01a) Sat May 15 20:10:24 2010
######################################################################

TEMPLATE = app
TARGET = cmpsim
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug
QT -= gui

# Input
SOURCES += main.cpp
